### ISSUE TITLE
Notes Section

### ISSUE THREAD

**Issue by Gross-Sweep** [felixphew/pokepaste#10]
Hey this is Gross Sweep, I'm an Auth in the Pokemon Showdown RMT room, and I wanted to say I really like the site. We are thinking of making it our go to site for sharing teams, but I do have one concern I'd like to bring up. The notes section is really small. If there was anyway to enlarge it I feel it would make the site perfect. Anyway that's it, and keep up the great work.

**Comment by felixphew** [comment]
The notes section should be user-resizeable with the little doohickey in the corner. Still, I'm happy to expand the default size.

**Comment by felixphew** [comment]
@Gross-Sweep Does 5 lines seem like enough to you?
