### ISSUE TITLE
New CAP art missing

### ISSUE THREAD

**Issue by photvedt** [felixphew/pokepaste#109]
Hey there, I'm a frequent CAP player and I noticed that the official CAP art on pokepastes is only up to Crucibelle. After doing a little investigating, it seems like there are files for Pajantom and Jumbao in your repository, but they don't seem to work on the site itself. 

Also, there's four new fully-evolved CAPs (Caribolt, Smokomodo, Snaelstrom, and Equilibra), whose art is found at these links:

- http://i.imgur.com/h4ONiEZ.png (Caribolt)
- https://puu.sh/Bpzbz.jpg (Smokomodo)
- http://i.imgur.com/cYb87TB.jpg (Snaelstrom)
- https://www.smogon.com/forums/attachments/1561055193240-png.181399/ (Equilibra)

Thanks for your time
- -Voltage-

**Comment by felixphew** [comment]
Thanks for poking me, and sorry about the extremely delayed response - I'll look into it!

**Comment by felixphew** [comment]
Fixed in #146. Sorry about the delay!
