### ISSUE TITLE
Fighting Gem Item Sprite

### ISSUE THREAD

**Issue by sbrvgc** [felixphew/pokepaste#11]
There is no sprite for the Fighting Gem, so a Pokémon holding one has no item sprite next to their sprite. This is unlike Pokémon holding other items, who have their held item's sprite next to their sprite.

**Comment by felixphew** [comment]
Confirmed with paste [c1b27a5be12c7175](http://pokepast.es/c1b27a5be12c7175) - the item isn't even being highlighted either. I wonder if this applies to all gems...

**Comment by felixphew** [comment]
Looks like all gems except Normal Gem are missing from `items.json`.
