### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by arttuoliver** [felixphew/pokepaste#111]
It doesnt work for me. I even copied the one that is in the format and it doesnt work. 

Talonflame @ Flyinium Z
Ability: Gale Wings
EVs: 252 Atk / 4 Def / 252 Spe
Jolly Nature
- Brave Bird
- Flare Blitz
- Swords Dance
- Roost
This was in the format but it doesnt work, it says No (or invalid) paste
pls help

**Comment by Kaiu24** [comment]
Talonflame (F) Flyinium Z
EVs: 252 Atk / 4 Def / 252 Spe
Ability: Gale Wings
Jolly Nature
- Brave Bird
- Flare Blitz
- Swords Dance
- Roost

Try this, it worked for me though the image doesnt appear

**Comment by Kaiu24** [comment]
Talonflame (F) Flyinium Z
EVs: 252 Atk / 4 Def / 252 Spe
Ability: Gale Wings
Jolly Nature
- Brave Bird
- Flare Blitz
- Swords Dance
- Roost

https://pokepast.es/bb34bffbc69e3a7f

**Comment by arttuoliver** [comment]
It doesn't work for me, i copied that text and it doesnt work

**Comment by Kaiu24** [comment]
Did you see the link I posted too? Try copying it from there

**Comment by Kaiu24** [comment]
Try paste as plain text

**Comment by arttuoliver** [comment]
got it to work, ty :P

**Comment by felixphew** [comment]
Hey @Kaiu24, thanks for helping this person out!
