### ISSUE TITLE
Any Updates?

### ISSUE THREAD

**Issue by Zelow79** [felixphew/pokepaste#119]
Could really use updated images for the Pokemon. A few suggestions are to maybe just add temp images until the ones you want are made, offer optional image sets that has the choice saved in cookies, or even an option to allow people to target their own folder with images and have that information saved to cookies. The last one I like the most tho since it would allow people to choose whatever image sets they like as well as making the site useful going forward in Gens even if you don't update the site, since it would allow the users to update the images themselves. Other than that tho I think you have a really cool site here and would love to see it keep going.

Zelow

**Comment by felixphew** [comment]
Fortunately, the images I want DO exist now! I'm just super busy with uni at the moment, and haven't tracked them to their source yet.

Your other ideas are cool, but way more effort than just putting the images I want up (also not sure how many people would utilise them).
