### ISSUE TITLE
The item Medichamite might be missing in the output

### ISSUE THREAD

**Issue by jhao7** [felixphew/pokepaste#123]
The issue existed when I tried to paste an ORAS OU team extracted from showdown team builder.
I tested seven mega stones, and Medichamite was the only one missing at the moment.
There is a proof as: https://pokepast.es/183ce6779536a2f2
Could you please have a look while available? I really appreciate this converter and it delights me. Thank you so much.

**Comment by felixphew** [comment]
Thanks for pointing this out! I had a closer look and Houndoominite was missing too. Both should be added now.

**Comment by jhao7** [comment]
> Thanks for pointing this out! I had a closer look and Houndoominite was missing too. Both should be added now.

Hi felixphew,

Thanks so much and I saw these two mega stones were already implemented. 

However, I had two findings which might deserve a looking, as the text colour of items sometimes could be a little bit inconsistent with others.

a) The text colour of Medichamite or Houndoomite would be fixed to dark red/brown now, while other mega stones would be all black/white based the on the settings of light mode. It is a clear inconsistency.

b) The text colour of power boost items (e.g. Mystic water/soft sand) would be synchronised to the colour of type it boosted (water - blue/ground - clay) now, while I found most other items (e.g. leftovers) would be black/white. Personally speaking, it would be only a minor inconsistency if all power boost items are synchronised to the colour of type it boosted. 

Thanks

**Comment by felixphew** [comment]
Hi @jhao7,

For a) (the mega stones), I set that by accident when I was fixing this issue - I thought I had them all highlighted like that, but I misremembered. This should be fixed now.

For b), this is intentional. All the type-boosting items are highlighted in their corresponding type, as are all plates (type boosting / for Arceus), memories (for Silvally), drives (for Genesect), gems, Z-crystals, incenses, and type-resist berries like Wacan (electric), Colbur (dark), Shuca (ground), etc.

**Comment by jhao7** [comment]
> Hi @jhao7,
> 
> For a) (the mega stones), I set that by accident when I was fixing this issue - I thought I had them all highlighted like that, but I misremembered. This should be fixed now.
> 
> For b), this is intentional. All the type-boosting items are highlighted in their corresponding type, as are all plates (type boosting / for Arceus), memories (for Silvally), drives (for Genesect), gems, Z-crystals, incenses, and type-resist berries like Wacan (electric), Colbur (dark), Shuca (ground), etc.

Yep. So that was why I said 'personally speaking" for the second finding. Quite appreciate for your devotion.
