### ISSUE TITLE
7 shadows of marshadow

### ISSUE THREAD

**Issue by victordoblew** [felixphew/pokepaste#14]
Marshadow @ Marshadium Z  
Ability: Technician  
EVs: 252 Atk / 4 SpD / 252 Spe  
Jolly Nature  
- Close Combat  
- Spectral Thief  
- Bulk Up  
- Shadow Sneak  

Groudon-Primal @ Red Orb  
Ability: Desolate Land  
EVs: 248 HP / 252 SpD / 8 Spe  
Careful Nature  
- Stealth Rock  
- Precipice Blades  
- Roar  
- Rock Slide  

Celesteela @ Leftovers  
Ability: Beast Boost  
EVs: 248 HP / 8 Def / 252 SpD  
Sassy Nature  
- Heavy Slam  
- Leech Seed  
- Flamethrower  
- Toxic  

Arceus-Dark @ Dread Plate  
Ability: Multitype  
EVs: 248 HP / 72 Def / 188 Spe  
Bold Nature  
IVs: 0 Atk  
- Judgment  
- Will-O-Wisp  
- Recover  
- Defog  

Salamence-Mega @ Salamencite  
Ability: Aerilate  
EVs: 16 HP / 252 Atk / 240 Spe  
Jolly Nature  
- Dragon Dance  
- Roost  
- Facade  
- Double-Edge  

Tapu Fini @ Leftovers  
Ability: Misty Surge  
EVs: 248 HP / 172 Def / 88 SpD  
Calm Nature  
IVs: 0 Atk  
- Whirlpool  
- Taunt  
- Moonblast  
- Nature's Madness

**Comment by felixphew** [comment]
I assume you're reporting the missing picture of Marshadow? If so, fixed.
