### ISSUE TITLE
Pokepaste Artwork

### ISSUE THREAD

**Issue by minkflow** [felixphew/pokepaste#149]
hey! I just wanted to send a message to Pokepaste that there is some upscaled Dream World/Pokemon Home/Global Link images for the 8th gen that would greatly improve the quality of the images that already exist as well as provide images for Galar versions. below I have provided a link that will send you to a google doc listing with links to the upscaled images. I personally did not make these but I think they'd be great for the website and I would definitely appreciate the move, thank you.

https://docs.google.com/spreadsheets/d/1VQkEWoiIT5UvNGn0Sal_9d9er6XqQ7PxvlBY0s649Og/edit#gid=0

**Comment by felixphew** [comment]
Thanks! I did take note of this when you first submitted the issue. I've now moved to using different images, so this is all taken care of.
