### ISSUE TITLE
Not creating pastes for all of my teams

### ISSUE THREAD

**Issue by Scopeowner** [felixphew/pokepaste#15]
Hi there,

I've been using this fantastic website to create pokepastes for all of my pokemon showdown team.I have 256 in total (spanning gen 1 to gen 7) and all was working fine until today. When I tried to create a new pokepaste for my teams, I get a message saying "**502 Bad Gateway**" **(nginx/1.10.3)**. I'm guessing this is a issue to do with the size of the pokepaste being generated, since I realised that it only generated pokepastes if I only used 50 teams instead of 256. 

Has a limit been introduced, or is this due to excess site trafiic? 

Can you please look into this matter?

Regards,

**Comment by felixphew** [comment]
As part of the migration to MySQL, a size limit has been introduced for pastes of approximately 64KiB (corresponding to the maximum size of TEXT).

When I built PokePaste, I intended it to be used for single teams at a time, certainly not for backing up hundreds of teams. However, I recognise that this is a legitimate and convenient use of the site.

I will consider updating the field size to MEDIUMTEXT (can't right now, I will this afternoon), and in the meantime, feel free to split your backup between a few pastes.

**Comment by Scopeowner** [comment]
Thanks felixphew for your quick response. When I paste all of teams on to notepad, the size of the file is 289KB, so if you can increase the limit to around range (like before) without any issues I'd appreciate that. Once again, many thanks for your response and I will patiently await your fix.

Regards

**Comment by felixphew** [comment]
I have updated the field to MEDIUMTEXT, which should have more than enough room for all your pastes. Thank you for informing me of this!

**Comment by Scopeowner** [comment]
Hi felixphew

Unfortunately, I'm still not able to create a pokepaste for my 256 teams (289KB file) as it still displays the "502 Bad Gateway" (nginx/1.10.3 on a blank screen. I have tried creating this pokepaste from different computers, but it's still not successful. :/ 

Are you sure the issue with the limit has been fixed? 

Regards

**Comment by felixphew** [comment]
Sorry, I made a stupid mistake by not restarting uwsgi, and as a result PokePaste has apparently been down all night 😲 It should be working now.
