### ISSUE TITLE
Poképast.es not working (Can't generate nor access pastes)

### ISSUE THREAD

**Issue by Sanchezuma** [felixphew/pokepaste#150]
Hi!

Ever since a few hours ago, I get the following error when trying to generate a new poképaste: 
`Error 1040: Too many connections`

And when trying to access and already generated poképaste, like [this one](https://pokepast.es/c032d9ef8ee69a57), I get this error:
`404 page not found`

Maybe you're already aware of this, but I thought it was worth opening an issue anyways since lots of people use this tool on a daily basis.

Many thanks.

**Comment by blankynoskills** [comment]
me too! i am having the same problem as well so now I can't show my paste to my friends. i hope this can be fixed soon! thanks!

**Comment by felixphew** [comment]
Hi - thanks for bringing this to my attention!

Not sure why this is, I'm looking into it right now.

**Comment by felixphew** [comment]
Haha - it looks like my server's drive is full!

Will try and expand it, but PokePaste'll likely be down for a little bit. Thanks again for bearing with me!

**Comment by felixphew** [comment]
Back up now!
