### ISSUE TITLE
CAP (Create-A-Pokemon) Pokemon

### ISSUE THREAD

**Issue by Scopeowner** [felixphew/pokepaste#16]
Hi felixphew,

This is not a major issue, and I wasn't really sure where I could suggest this idea. Smogon has a set of CAP pokemon that are fan made and have been accepted by them (a total of 22). It does have it's own format of play as well on Pokemon Showdown. I know these CAP pokemon are not official (not created by GameFreak) but it would be really nice to add sprites for these pokemon. I know you may have to go out of your for this request, but I'd really appreciate it if you could add support for CAP pokemon.

Please let me know if you need any more clarification, the page where you can find these pokemon is here
http://www.smogon.com/cap/pokemon/

Best Regards,

**Comment by felixphew** [comment]
Thanks for mentioning this - someone [you?] already raised the idea on the Smogon forums. All I was waiting on was artwork, which your link seems to include, so I should be able to get this implemented relatively soon (it doesn't actually require any code changes, I just add the mons to `pokemon.json`).

**Comment by Scopeowner** [comment]
Many thanks for responding to my suggestions felixphew. Please keep me posted on this enchancement and let me know once it's all up and running on PokePaste.

**Comment by felixphew** [comment]
http://pokepast.es/9463036133dd7fba

Sorry it took me a while to push it to the live site, I had internet issues yesterday.

**Comment by Scopeowner** [comment]
Looks perfect felixphew, many thanks for adding this cool enhancement.
