### ISSUE TITLE
Minimalist ad banner on site

### ISSUE THREAD

**Issue by codybye** [felixphew/pokepaste#169]
Hey team - I'd love to see if my company (NitroPay.com) could help out by getting a minimalist ad placement put on the site. I'm thinking just one slot, probably along the bottom of the page so as not to cover code/information. 

Let me know! You can reach me here, cody@ggsoftware.io, or Discord at CodyBye#2791

**Comment by felixphew** [comment]
Hi Cody - thanks for your offer! I believe someone from your company made an offer like this once before, but perhaps it was another company.

I currently have no intention to run ads on PokePaste - I deliberately keep the site footprint as low as possible to enable me to run it sustainably out of my own pocket. As a result, running costs are actually rather minimal.

If I ever reconsider this position, though, I'll let you know!
