### ISSUE TITLE
Some items missing images

### ISSUE THREAD

**Issue by lino49** [felixphew/pokepaste#18]
Some items (notably some mega stones) don't have the images on the site, here's a list

Abomasite
Aggronite
Altarianite
Ampharosite
Audinite
Banettite
Beedrillite
Blazikenite
Cameruptite
Diancite
Galladite
Gardevoirite
Heracronite
Houndoomite
Latiasite
Latiosite
Lopunnite
Manectite
Mawilite
Pidgeotite
Sceptilite
Steelixite
Swampertite
Tyranitarite

As well as the image of Custap Berry that's missing, noticed it when i wanted to put some old gen teams

**Comment by lino49** [comment]
and oh didnt check if Mewtwonite X and Mewtwonite Y had their images

**Comment by felixphew** [comment]
Thanks so much for this! I'm going to be pretty flat-out with school stuff for the next week or so, but I'll try to add these as soon as I can.

**Comment by lino49** [comment]
yw

**Comment by lino49** [comment]
Also, King's Rock doesn't have an image either

**Comment by lino49** [comment]
remind

**Comment by felixphew** [comment]
Sorry I took so long about this - I really need to regenerate all the item databases (hence why I'll leave this issue open), but this should do as a stopgap solution at least.

**Comment by lino49** [comment]
Ow, thanks =D

**Comment by lino49** [comment]
Ow, noticed that you forgot the Medichamite ;)

**Comment by felixphew** [comment]
With the new codebase, I *think* this should all be taken care of.
