### ISSUE TITLE
All of my sets are gone

### ISSUE THREAD

**Issue by BlondeSasukeUchiha** [felixphew/pokepaste#24]
https://pokepast.es/53b90f6fe195c0ec
All of my sets were at this link and now it wont open
why is this?

**Comment by felixphew** [comment]
![](https://user-images.githubusercontent.com/3969114/32524693-16c3ac06-c475-11e7-88d7-c425618923e9.png)
Sorry, I was having an issue with the new site - it should be back now.

**Comment by felixphew** [comment]
The link is definitely working for me now, so I'm closing this issue - let me know if it's still broken for you @BlondeSasukeUchiha.
