### ISSUE TITLE
Mr. Mime and Mime Jr. are not recognized

### ISSUE THREAD

**Issue by Chriscftb97** [felixphew/pokepaste#26]

**Comment by felixphew** [comment]
Thanks - I know what's causing this, one sec

**Comment by felixphew** [comment]
I won't be able to push this to the live version of the site for a few hours unfortunately, because I have an exam - but it's fixed.

**Comment by felixphew** [comment]
Ok, @Chriscftb97 I've just pushed the changes, and it's working for me ([02ab53aae0ef455a](http://pokepast.es/02ab53aae0ef455a))
