### ISSUE TITLE
Pajantom

### ISSUE THREAD

**Issue by sleepiemeepie** [felixphew/pokepaste#29]
Really minor one here and I don't put you at fault at all (since the Pokemon just released yesterday) but Pajantom is a CAP mon that is finished, and it's something I'd like to see added!

Have some art: https://i.imgur.com/PUOV3wp.png

**Comment by felixphew** [comment]
Thanks, I'll do it in a few hours. Do you have the type for me?

**Comment by sleepiemeepie** [comment]
Dragon/Ghost :)

**Comment by felixphew** [comment]
Dragon primary? (It matters)

**Comment by sleepiemeepie** [comment]
Yep, Dragon's the primary type.

**Comment by felixphew** [comment]
Looks like it's working for [adfe453f145af937](https://pokepast.es/adfe453f145af937).
