### ISSUE TITLE
Kommo-o comes out blank

### ISSUE THREAD

**Issue by FlareblastZed** [felixphew/pokepaste#30]
http://pokepast.es/e8cc28916dda539f

**Comment by felixphew** [comment]
I actually already knew about this, I should be able to fix it this afternoon.

**Comment by FlareblastZed** [comment]
Thanks, keep up the good work! I love using Pokepaste.

**Comment by felixphew** [comment]
Looks like it's working for [4d78bef0d77d3580](http://pokepast.es/4d78bef0d77d3580).
