### ISSUE TITLE
UU birdkeepertoby tournament

### ISSUE THREAD

**Issue by MaartenDJ27** [felixphew/pokepaste#33]

**Comment by felixphew** [comment]
Hi @MaartenDJ27,
What exactly is your issue?

**Comment by MaartenDJ27** [comment]
Oh I tried to make a teamspread here (for advice) but I didn't know how to make it work

**Comment by felixphew** [comment]
You click in the main black area (see where it says "Paste something here!"), and paste in your team from Showdown or wherever. Then, in the sidebar, you can add a title and stuff if you like, and hit "Submit Paste".

**Comment by MaartenDJ27** [comment]
Ah thanks I see it now, I just looked over the submit past button

**Comment by felixphew** [comment]
No problem!
