### ISSUE TITLE
Fighting-type color is wrong

### ISSUE THREAD

**Issue by MandL27** [felixphew/pokepaste#34]
Currently, both Fire and Fighting use an orange color in moves.
![image](https://user-images.githubusercontent.com/10366615/33851024-b6e61a0c-de83-11e7-8cb2-daf655da8995.png)
![image](https://user-images.githubusercontent.com/10366615/33851032-bd4c9c9a-de83-11e7-8246-8f5b57c6e42f.png)
However, in-game, the Fighting type is represented with a reddish brown color.
![image](https://user-images.githubusercontent.com/10366615/33851060-d3abd55a-de83-11e7-89db-da02857d2759.png)
This bug makes it hard to differentiate between the two at a glance, defeating the purpose of syntax-highlighting moves (and Pokémon) by type.

**Comment by felixphew** [comment]
Ok, I don't know how that happened! You're right that the colour is wrong, I meant to use #C03028 for fighting.

**Comment by felixphew** [comment]
@MandL27 You should be able to see the new colour, although you might have to force reload / clear cache to get it to appear. ([Example paste](https://pokepast.es/601665a0c118370f).)

**Comment by MandL27** [comment]
Yep, it's fixed. Thanks.
