### ISSUE TITLE
Error when Submitting team.

### ISSUE THREAD

**Issue by TickleMeChad** [felixphew/pokepaste#35]
Hello, for the past month I keep getting the following error when I submit my teams from Pokemon Showdown.
![error](https://user-images.githubusercontent.com/34974616/34458673-30b30316-eda9-11e7-8fb5-fba479a225f3.png)

**Comment by felixphew** [comment]
@TickleMeChad Yep, I'm getting it at that address too - I'm assuming the code is choking on your team for some reason. One sec, I'll look into it.

**Comment by felixphew** [comment]
My hunch is that the ツ character in ¯\_(ツ)_/¯ is causing some problems - it *shouldn't*, but it probably is...

**Comment by felixphew** [comment]
Here's the [error log](https://github.com/felixphew/pokepaste/files/1594948/error.log) - MySQL connection is being dropped for some reason. Encoding issue maybe?

**Comment by felixphew** [comment]
OH! I see the problem @TickleMeChad - you've pasted the team into the "notes" box, leaving the paste itself blank (which is invalid). Paste the team into the large black area.

**Comment by BlueScalePoseidon** [comment]
![image](https://user-images.githubusercontent.com/54163208/63140979-df6ba080-bfb1-11e9-8196-f7fdb33390a8.png)

![image](https://user-images.githubusercontent.com/54163208/63140950-c662ef80-bfb1-11e9-8f4b-5bb019e0809a.png)


Trying to submit my team for a tournament, but it is not working at all. I followed the steps to the letter. Is there something I am missing here?

**Comment by BlueScalePoseidon** [comment]
I also tried multiple browsers as well.

**Comment by felixphew** [comment]
Hi @BlueScalePoseidon, try pasting your team into the big black area on the left, not the little “Notes” field.

**Comment by BlueScalePoseidon** [comment]
Got it. Thanks.
