### ISSUE TITLE
Issue with displaying the color of U-turn

### ISSUE THREAD

**Issue by sleepiemeepie** [felixphew/pokepaste#36]
For some reason, U-turn displays as a Normal-type move, when it should be a Bug-type move.
![image](https://user-images.githubusercontent.com/34075236/34546610-f7f8ba76-f0c2-11e7-829a-e06ddc75cd6e.png)

**Comment by felixphew** [comment]
That's not Normal-type, that means it's not recognised (and I think I know why).

**Comment by felixphew** [comment]
Should be working now (tested for [a8bd1a315b86606f](https://pokepast.es/a8bd1a315b86606f)).
