### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by nir-elgad** [felixphew/pokepaste#40]
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
What do i do?

**Comment by felixphew** [comment]
@SuperPartrix can you send me the link to the team that was giving you this error?

**Comment by nir-elgad** [comment]
@felixphew copied straight from Showdown

Doggo (Houndoom-Mega) (M) @ Houndoominite  
Ability: Flash Fire  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Nasty Plot  
- Dark Pulse  
- Flamethrower  
- Sludge Bomb  

Excalibur (Doublade) (M) @ Eviolite  
Ability: No Guard  
EVs: 252 HP / 252 Atk / 4 SpD  
Adamant Nature  
- Swords Dance  
- Shadow Claw  
- Shadow Sneak  
- Sacred Sword  

Belle (Sylveon) (F) @ Leftovers  
Ability: Pixilate  
Shiny: Yes  
EVs: 252 HP / 252 Def / 4 SpD  
Calm Nature  
IVs: 0 Atk  
- Wish  
- Protect  
- Hyper Voice  
- Heal Bell  

Mr. Frog (Seismitoad) (M) @ Leftovers  
Ability: Water Absorb  
EVs: 252 HP / 196 Def / 60 Spe  
Impish Nature  
- Scald  
- Earthquake  
- Toxic  
- Stealth Rock  

Narcissa (Latias) @ Choice Scarf  
Ability: Levitate  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Draco Meteor  
- Ice Beam  
- Trick  
- Defog  

Iron Lady (Scizor) (F) @ Leftovers  
Ability: Technician  
EVs: 248 HP / 124 Def / 136 SpD  
Impish Nature  
- Swords Dance  
- Roost  
- U-turn  
- Bullet Punch  

It happens on every team i tried till now

**Comment by felixphew** [comment]
I'm sorry @SuperPartrix, I can't work out what was going wrong for you. That team seems to paste fine for me.

I know this can be frustrating, but without more information there's not much more I can do.
