### ISSUE TITLE
how can i past a team to my frend in showdown

### ISSUE THREAD

**Issue by thepokemaniac** [felixphew/pokepaste#42]
i dont know how to pas a team for my friend plese help me here is  the team that i wanted to share with my friend

Latias @ Latiasite  
Ability: Levitate  
Shiny: Yes  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Psychic  
- Psyshock  
- Calm Mind  
- Draco Meteor  

Latios @ Sitrus Berry  
Ability: Levitate  
Shiny: Yes  
EVs: 252 HP / 4 SpD / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Light Screen  
- Defog  
- Roost  
- Toxic  

Mimikyu-Busted @ Mimikium Z  
Ability: Disguise  
Shiny: Yes  
EVs: 4 Atk / 252 SpA / 252 Spe  
Hasty Nature  
- Dark Pulse  
- Play Rough  
- Psychic  
- Shadow Ball  

Type: Null @ Leftovers  
Ability: Battle Armor  
EVs: 252 HP / 252 Atk / 4 SpD  
Adamant Nature  
- Swords Dance  
- Iron Head  
- Rock Slide  
- Shadow Claw  

Thundurus @ Choice Scarf  
Ability: Prankster  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature  
IVs: 1 Atk  
- Hidden Power [Ice]  
- Grass Knot  
- Thunderbolt  
- Sludge Bomb  

Tapu Lele @ Leftovers  
Ability: Psychic Surge  
EVs: 252 HP / 252 SpA / 4 SpD  
Modest Nature  
IVs: 0 Atk  
- Aromatherapy  
- Moonblast  
- Taunt  
- Shadow Ball

**Comment by felixphew** [comment]
Hi @thepokemaniac, sorry for taking so long to get back to you.

Go to <https://pokepast.es>, and paste your team into the big black block on the left. You can add a title and stuff on the right if you want, then click "Submit Paste!". It should redirect you to a formatted version of your paste. Copy the address out of the address bar and send it to your friend.

Let me know how you go!
