### ISSUE TITLE
No Image for Berserk Gene

### ISSUE THREAD

**Issue by Zrp200** [felixphew/pokepaste#43]

**Comment by felixphew** [comment]
Thanks @Zrp200 - there is no Global Link artwork (or any other reasonable-resolution artwork, as far as I know) for the Berserk Gene, as it hasn't existed in-game since Generation II. If you find one, either official, or fan-made with permission for me to use it, let me know.

**Comment by Zrp200** [comment]
I got this from the Pokemon Showdown teambuilder, literally the only hit I got (obtained via screengrab).
![berserk gene](https://user-images.githubusercontent.com/7078074/36451793-1d0b04be-1647-11e8-94af-ce844d5d57e7.PNG)

**Comment by Zrp200** [comment]
@felixphew

**Comment by felixphew** [comment]
Thanks, but I have no idea where that's from and it's a bit low-res. I think I'll just leave that one out (no offence to anyone who plays Gen II!)

**Comment by Zrp200** [comment]
what resolution would you prefer?

**Comment by felixphew** [comment]
It's more that it's not in the same visual style as all the other images. Also, it's one of several early-generation items I'm messing, and I feel I would want to add all of those at once.

**Comment by Zrp200** [comment]
Which would you be interested in?
