### ISSUE TITLE
Time Volt-Turn UU

### ISSUE THREAD

**Issue by NionUgnis** [felixphew/pokepaste#44]
Florzinha (Celebi) @ Leftovers  
Ability: Natural Cure  
Shiny: Yes  
EVs: 252 HP / 4 SpA / 252 Spe  
Hasty Nature  
- U-turn  
- Psychic  
- Giga Drain  
- Recover  

marquinhos (Manectric) (M) @ Manectite  
Ability: Lightning Rod  
Shiny: Yes  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Volt Switch  
- Thunderbolt  
- Flamethrower  
- Hidden Power [Ice]  

Vaiser (Muk-Alola) (M) @ Assault Vest  
Ability: Poison Touch  
Shiny: Yes  
EVs: 252 HP / 252 Atk / 4 SpD  
Adamant Nature  
- Pursuit  
- Knock Off  
- Poison Jab  
- Fire Punch  

soco bala (Scizor) (M) @ Metal Coat  
Ability: Technician  
EVs: 252 HP / 252 Atk / 4 Def  
Adamant Nature  
- Bullet Punch  
- U-turn  
- Roost  
- Swords Dance  

Vovó Tala (Mantine) (F) @ Leftovers  
Ability: Water Absorb  
EVs: 248 HP / 156 Def / 104 SpD  
Calm Nature  
IVs: 0 Atk  
- Defog  
- Roost  
- Scald  
- Toxic  

suco (Gliscor) (M) @ Toxic Orb  
Ability: Poison Heal  
EVs: 252 HP / 4 Atk / 252 Spe  
Jolly Nature  
- Earthquake  
- Ice Fang  
- Substitute  
- Roost

**Comment by felixphew** [comment]
Hi @NionUgnis - that team seems to be pasting fine for me (<http://pokepast.es/ea1ce44b60b250e7>), what was your issue?

**Comment by felixphew** [comment]
I'm going to close this issue now unless you've got a specific problem.
