### ISSUE TITLE
Improper Highlighting for Type Related Items

### ISSUE THREAD

**Issue by AuraStormLucario** [felixphew/pokepaste#48]
Hi.  Firstly, thank you so much for everything you've done to create this, I think the community appreciates it more than you could ever believe.  

Over my time using pokepaste, I have noticed missing highlights from certain items related to a specific type, whereas other items relating to that same type do have the appropriate highlighting.  I've provided two examples here: <a href="http://pokepast.es/07397376a4f931c1">ice type</a> and <a href="http://pokepast.es/d819bc04ca21b17d">fire type</a>.  With your permission, I would like to attempt to code a fix for this myself, which I can then create a pull request for.

**Comment by felixphew** [comment]
Thanks for bringing this to my attention!

You shouldn't have to code anything, it should just be a matter of adding some types to `items.json`, but feel free to give it a go. If not, I'll get onto it soon.

**Comment by felixphew** [comment]
And in future, you don't have to ask permission to try and code something (although you can) - just give it a go and send me a PR. Worst case scenario is I can't pull the change, which is unlikely.

**Comment by AuraStormLucario** [comment]
Alright, this should be very easy then (although a little tedious).  I'll do this tonight.  

(One unrelated note, I think Issues #44 #45 and maybe #47 could maybe be closed now).

**Comment by AuraStormLucario** [comment]
In the items.json file, about 20 mega stones are at the bottom of the list in order of their id instead of being in the main list.  If I move all the megastones to the bottom, I would think it would stand to reason that Z-items, Gems, Plates, Memory Items, etc. should all be grouped together as well.  Do you have any preference?  If not, should I just move the 20 mega stones back into the main list?

**Comment by felixphew** [comment]
The order of that list is largely irrelevant, but if you want to make everything consistent then it's probably easier to put the mega stones in with the main list.
