### ISSUE TITLE
M-Latias muerde el cebo

### ISSUE THREAD

**Issue by DanMast** [felixphew/pokepaste#51]
Nihilego @ Focus Sash  
Ability: Beast Boost  
Level: 50  
EVs: 4 HP / 252 SpA / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Sludge Bomb  
- Power Gem  
- Hidden Power [Ice]  
- Protect  

Latias-Mega @ Latiasite  
Ability: Levitate  
Level: 50  
EVs: 140 HP / 52 Def / 60 SpA / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Draco Meteor  
- Calm Mind  
- Psyshock  
- Roost  

Suicune @ Choice Specs  
Ability: Pressure  
Level: 50  
Shiny: Yes  
EVs: 4 HP / 252 SpA / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Hydro Pump  
- Ice Beam  
- Scald  
- Hidden Power [Grass]  

Kaku Topo (Tapu Koko) @ Electrium Z  
Ability: Electric Surge  
Level: 50  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Thunderbolt  
- Thunder  
- Dazzling Gleam 
- Protect  

Incineroar @ Assault Vest  
Ability: Intimidate  
Level: 50  
EVs: 252 HP / 252 Atk / 4 SpD  
Adamant Nature  
- Fake Out  
- Flare Blitz  
- Knock Off  
- Superpower  

Togekiss @ Aguav Berry  
Ability: Serene Grace  
Level: 50  
Shiny: Yes  
EVs: 244 HP / 92 Def / 172 SpD  
Calm Nature  
IVs: 0 Atk  
- Encore  
- Tailwind  
- Follow Me  
- Roost

**Comment by felixphew** [comment]
Hi, this is an issue tracker, not a place to paste your teams. If you have an issue let me know, otherwise I'm closing this issue.
