### ISSUE TITLE
No image for Zeraora

### ISSUE THREAD

**Issue by Chriscftb97** [felixphew/pokepaste#57]

**Comment by felixphew** [comment]
Hi @Chriscftb97,
As far as I'm aware, there's no official Dream World art for Zeraora yet. I'll double-check tonight whether this is still the case.

**Comment by felixphew** [comment]
OK, this should be fixed now (confirmed for [a753a76247ca87db](https://pokepast.es/a753a76247ca87db)). Sorry about the delay.
