### ISSUE TITLE
Is this good?

### ISSUE THREAD

**Issue by Electro-Xx** [felixphew/pokepaste#58]
Rayquaza-Mega @ Life Orb  
Ability: Delta Stream  
EVs: 252 Atk / 4 Def / 252 Spe  
Adamant Nature  
- Dragon Ascent  
- Earthquake  
- Extreme Speed  
- Dragon Dance  

Marshadow @ Life Orb  
Ability: Technician  
EVs: 4 HP / 252 Atk / 252 Spe  
Adamant Nature  
- Spectral Thief  
- Hidden Power [Ice]  
- Close Combat  
- Shadow Sneak  

Arceus-Fairy @ Pixie Plate  
Ability: Multitype  
EVs: 252 HP / 128 Def / 128 SpA  
Bold Nature  
IVs: 0 Atk  
- Judgment  
- Stealth Rock  
- Psychic  
- Recover  

Smeargle @ Focus Sash  
Ability: Technician  
EVs: 252 HP / 4 Atk / 252 Spe  
Jolly Nature  
- Nuzzle  
- Taunt  
- Sticky Web  
- Stealth Rock  

Arceus-Steel @ Iron Plate  
Ability: Multitype  
EVs: 252 HP / 252 Def / 4 SpA  
Bold Nature  
IVs: 0 Atk  
- Judgment  
- Defog  
- Calm Mind  
- Recover  

Toxapex @ Black Sludge  
Ability: Regenerator  
EVs: 248 HP / 252 Def / 8 SpD  
Bold Nature  
IVs: 0 Atk  
- Scald  
- Recover  
- Toxic Spikes  
- Haze

**Comment by felixphew** [comment]
Hi @Electro-Xx!

Your team looks pretty good to me, but this is actually a bug tracker for reporting problems with pokepast.es, not a place to submit teams. If you're having any issues with the site, let me know.
