### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Storm-Eagle20** [felixphew/pokepaste#60]
The time is currently 1:29 AM, the errors were encountered around 1:24 AM. This is Eastern US Time, -5:00 hours. I tried pasting this team and it doesn't work.

Mamoswine @ Metronome  
Ability: Thick Fat  
Shiny: Yes  
EVs: 252 Atk / 4 SpD / 252 Spe  
Jolly Nature  
- Earthquake  
- Ice Shard  
- Icicle Crash  
- Stealth Rock  

Kartana @ Choice Scarf  
Ability: Beast Boost  
Shiny: Yes  
EVs: 4 HP / 252 Atk / 252 Spe  
Adamant Nature  
- Leaf Blade  
- Smart Strike  
- Knock Off  
- Sacred Sword  

Gastrodon-East @ Leftovers  
Ability: Storm Drain  
Shiny: Yes  
EVs: 248 HP / 8 Def / 252 SpD  
Sassy Nature  
IVs: 0 Atk  
- Scald  
- Recover  
- Toxic  
- Ice Beam  

Clefable @ Leftovers  
Ability: Magic Guard  
EVs: 252 HP / 252 Def / 4 SpD  
Bold Nature  
IVs: 0 Atk  
- Moonblast  
- Soft-Boiled  
- Fire Blast  
- Calm Mind  

Gyarados @ Gyaradosite  
Ability: Intimidate  
Shiny: Yes  
EVs: 4 HP / 252 Atk / 252 Spe  
Serious Nature  
- Dragon Dance  
- Earthquake  
- Crunch  
- Waterfall  

Tornadus-Therian @ Flyinium Z  
Ability: Regenerator  
Shiny: Yes  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature  
- Hurricane  
- Knock Off  
- U-turn  
- Defog

**Comment by felixphew** [comment]
Hi @Storm-Eagle20, and thanks for letting me know about this. I'll hopefully have time to look into the root cause this evening, but in the meantime, here is your paste:

http://pokepast.es/01154ee19035c94d

**Comment by Storm-Eagle20** [comment]
Did you find the error by any chance? Would you also be willing to paste this one more time, instead fix Gyarados's nature? I accidentally made it Serious natured when it was intended to be Jolly. I forgot to change the nature before I pasted.

**Comment by Storm-Eagle20** [comment]
So uh... I found out the cause of the issue. Turns out I was being an idiot and pasting the team in the notes section. I am very, _very_ sorry for wasting your time and I couldn't actually see the 'Paste something here' because of the glare on my TV. You should probably add some sort of exception to prevent notes-only pastes from going through.

**Comment by felixphew** [comment]
All good! You're definitely not the only person to do that. I do think the website layout is a little unintuitive but people are largely used to it now so I'm hesitant to change it.
