### ISSUE TITLE
No image for CAP24!

### ISSUE THREAD

**Issue by sleepiemeepie** [felixphew/pokepaste#61]
Smogon recently finished their newest CAP, Jumbao. I noticed that it doesn't have any info yet, so here's the important stuff:

**PRIMARY TYPE**:  Grass

**ARTWORK**: 
![image](https://user-images.githubusercontent.com/34075236/40497195-a0886aa2-5f49-11e8-92bd-8ccb3d1ae20d.png)

**NAME**: Jumbao

Thank you! :)

**Comment by felixphew** [comment]
Thanks, I'm adding it now.
