### ISSUE TITLE
Internal Server Error?

### ISSUE THREAD

**Issue by NylaTheWolf** [felixphew/pokepaste#67]
Whenever I try to paste a new team, it gives me an Internal Server Error.
<img width="1083" alt="screen shot 2018-07-27 at 11 18 08 am" src="https://user-images.githubusercontent.com/41797151/43329575-c5fa515c-918e-11e8-91c9-26e0e83838ed.png">

I don't know why this is happening, as I don't think my format is off. I pasted it directly from Pokemon Showdown.

This was the team I was trying to paste: 

Razor (Excadrill) (M) @ Focus Sash  
Ability: Mold Breaker  
EVs: 252 Atk / 4 Def / 252 Spe  
Jolly Nature  
- Stealth Rock  
- Rock Slide  
- Earthquake  
- Iron Head  

Breezepelt (Weavile) (M) @ Choice Band  
Ability: Pressure  
EVs: 252 Atk / 4 SpD / 252 Spe  
Jolly Nature  
- Icicle Crash  
- Knock Off  
- Ice Shard  
- Pursuit  

Haikili (Tapu Koko) @ Shuca Berry  
Ability: Electric Surge  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature  
- Thunderbolt  
- Defog  
- U-turn  
- Hidden Power [Ice]  

Riptide (Gyarados) (M) @ Flyinium Z  
Ability: Moxie  
EVs: 252 Atk / 4 SpD / 252 Spe  
Jolly Nature  
- Dragon Dance  
- Bounce  
- Waterfall  
- Earthquake  

Arcane (Alakazam-Mega) (M) @ Alakazite  
Ability: Magic Guard  
EVs: 4 Def / 252 SpA / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Psychic  
- Focus Blast  
- Shadow Ball  
- Hidden Power [Fire]  

Hawkeye (Hawlucha) (M) @ Electric Seed  
Ability: Unburden  
EVs: 96 HP / 252 Atk / 36 SpD / 124 Spe  
Adamant Nature  
- Acrobatics  
- Swords Dance  
- High Jump Kick  
- Roost  

Is this just me, or is there an issue with the site? Thank you for reading, and have a fantastic day!

**Comment by felixphew** [comment]
Hi @NylaTheWolf,

Thanks for filing this, and sorry I didn't get back to you earlier. This was a known issue with PokePaste v2, and it should be fixed now that I've deployed v3.

If you're still running into this, please let me know and re-open.

**Comment by NylaTheWolf** [comment]
It's cool!

Alrighty, thanks so much!
