### ISSUE TITLE
aaa

### ISSUE THREAD

**Issue by kid520** [felixphew/pokepaste#69]
Sneasel @ Choice Band  
Ability: Inner Focus  
EVs: 252 Atk / 4 SpD / 252 Spe  
Jolly Nature  
- Ice Shard  
- Pursuit  
- Icicle Crash  
- Knock Off  

Slowbro @ Waterium Z  
Ability: Regenerator  
EVs: 244 HP / 232 Def / 24 SpD / 8 Spe  
Bold Nature  
IVs: 0 Atk  
- Calm Mind  
- Slack Off  
- Psyshock  
- Scald  

Steelix @ Leftovers  
Ability: Rock Head  
EVs: 244 HP / 240 SpD / 24 Spe  
Careful Nature  
- Stealth Rock  
- Heavy Slam  
- Earthquake  
- Toxic  

Golbat @ Eviolite  
Ability: Infiltrator  
EVs: 248 HP / 4 Def / 196 SpD / 60 Spe  
Careful Nature  
- Defog  
- Roost  
- Brave Bird  
- Taunt  

Audino @ Audinite  
Ability: Regenerator  
EVs: 252 HP / 4 Def / 252 SpD  
Careful Nature  
- Wish  
- Protect  
- Knock Off  
- Heal Bell  

Pyukumuku @ Leftovers  
Ability: Unaware  
EVs: 248 HP / 252 Def / 8 SpD  
Bold Nature  
IVs: 0 Atk  
- Block  
- Spite  
- Recover  
- Toxic

**Comment by felixphew** [comment]
Hi @kid520,

This is actually an issue tracker for reporting bugs in PokePaste - not the place to paste your teams!

If you have an issue, let me know what it is and I'll have a look at it. Otherwise, paste your team into the big black box at https://pokepast.es.
