### ISSUE TITLE
404 Error in link to syntax.html

### ISSUE THREAD

**Issue by frozenpandaman** [felixphew/pokepaste#70]
https://github.com/felixphew/pokepaste/blob/e5325044272b57940936edc490e03dc8212bf3f8/assets/index.html#L27

404 Error. Should lead to `syntax.html`, not just `syntax`.

**Comment by felixphew** [comment]
Thanks, I just forgot about this. I'm actually hoping to find a relatively clean way to make `syntax` work, without making a `syntax/index.html`.

**Comment by frozenpandaman** [comment]
I'm not too familiar with Go, so not sure if there's some way to do it there, but if you have access to the `.htaccess` file on the server where this is being hosted it should be easy to do with URL rewriting.

**Comment by felixphew** [comment]
There is no `.htaccess`, no Apache, no nothing - PokePaste is its own web server. And yes, I could do it in code, but that either forces me to make it a special case or treat it as a template, neither of which I'd really like to do.

**Comment by frozenpandaman** [comment]
Ooooh I see. Guess I could've maybe guessed that by looking at the repo structure… Not sure what to suggest, sorry, but hoping you find a way to do it satisfactorily!

**Comment by nickswang** [comment]
add a file named "syntax" thats a symlink to "syntax.html"? @felixphew

**Comment by Th3Alic3** [comment]
Shoot. I just posted as this issue is either a repeat or still going on!
