### ISSUE TITLE
no (or Invalid) paste

### ISSUE THREAD

**Issue by ISuckAtProgramming** [felixphew/pokepaste#82]
No matter what I change I get a No (or Invalid) error. I am coping directly from Showdown. Here is the format of the team:

Clefable @ Leftovers  
Ability: Magic Guard  
EVs: 252 HP / 252 Def / 4 SpD  
Bold Nature  
IVs: 0 Atk  
- Calm Mind  
- Moonblast  
- Soft-Boiled  
- Thunder Wave  

Greninja-Ash @ Choice Specs  
Ability: Battle Bond  
EVs: 4 HP / 252 SpA / 252 Spe  
Timid Nature  
- Spikes  
- Water Shuriken  
- Dark Pulse  
- Hydro Pump  

Tyranitar-Mega @ Tyranitarite  
Ability: Sand Stream  
EVs: 168 HP / 252 Atk / 88 Spe  
Adamant Nature  
- Stealth Rock  
- Pursuit  
- Stone Edge  
- Fire Punch  

Tangrowth (M) @ Assault Vest  
Ability: Regenerator  
EVs: 248 HP / 8 Def / 252 SpD  
Sassy Nature  
- Giga Drain  
- Earthquake  
- Sludge Bomb  
- Rock Slide  

Excadrill @ Steelium Z  
Ability: Sand Rush  
EVs: 252 Atk / 4 SpD / 252 Spe  
Adamant Nature  
- Swords Dance  
- Iron Head  
- Earthquake  
- Rapid Spin  

Tapu Koko @ Choice Scarf  
Ability: Electric Surge  
EVs: 4 HP / 252 Atk / 252 Spe  
Naughty Nature  
- Wild Charge  
- Brave Bird  
- Hidden Power [Ice]  
- U-turn  

It imports correctly in Showdown, but not paste. Also, the format page is still broken, but I'm sure you know that.

PS: Github seems to turn - into bullet points, but I assure you that its -

**Comment by felixphew** [comment]
Hi @ISuckAtProgramming,

Sorry to ask the obvious question, but are you pasting the team into the big black area to the left, or into the "notes" field on the right?

Your team appears to paste fine to me:
<https://pokepast.es/f50557cb8301bd65>

Thanks,
\- Felix

**Comment by dounothemffnman** [comment]
I'm getting the same problem but with this team

Slowking @ Psychium Z  
Ability: Regenerator  
EVs: 252 HP / 252 SpA / 4 SpD  
Quiet Nature  
IVs: 0 Atk  
- Scald  
- Psychic  
- Nasty Plot  
- Trick Room  

Xatu @ Rocky Helmet  
Ability: Magic Bounce  
EVs: 248 HP / 200 Def / 60 Spe  
Impish Nature  
- Night Shade  
- Toxic  
- U-turn  
- Roost  

Abomasnow-Mega (M) @ Abomasite  
Ability: Snow Warning  
EVs: 28 HP / 252 SpA / 228 Spe  
Mild Nature  
- Blizzard  
- Earthquake  
- Ice Shard  
- Giga Drain  

Weezing @ Black Sludge  
Ability: Levitate  
Happiness: 0  
EVs: 252 HP / 200 Def / 56 Spe  
Bold Nature  
IVs: 0 Atk  
- Toxic Spikes  
- Flamethrower  
- Pain Split  
- Sludge Bomb  

Passimian @ Choice Scarf  
Ability: Defiant  
EVs: 252 Atk / 4 SpD / 252 Spe  
Jolly Nature  
- U-turn  
- Close Combat  
- Knock Off  
- Gunk Shot  

Steelix @ Life Orb  
Ability: Sheer Force  
EVs: 172 HP / 252 SpA / 84 Spe  
Modest Nature  
IVs: 0 Atk  
- Flash Cannon  
- Earth Power  
- Stealth Rock  
- Dark Pulse  

im putting it in the notes field

**Comment by felixphew** [comment]
Hi @ISuckAtProgramming,

That'd be your problem! "No paste" means there is nothing in the big paste field to the left, which will cause the server to reject your paste. Try pasting your team there instead of the notes field and let me know how you go.

Thanks,

- Felix
