### ISSUE TITLE
No (or invalid) paste

### ISSUE THREAD

**Issue by shantanudeshp** [felixphew/pokepaste#84]
As in the title. I get the error even with correct formatting. When I click to check the format, I get a 404 error.

**Comment by felixphew** [comment]
Hi @shantanudeshp , are you pasting the team into the "notes" box? Try pasting it into the big black area to the left.

**Comment by shantanudeshp** [comment]
I just realized that, thanks for bearing with me! :)

**Comment by felixphew** [comment]
No problem!
