### ISSUE TITLE
Feature Request: Import through PokePaste Link

### ISSUE THREAD

**Issue by HarounAns** [felixphew/pokepaste#94]
I have a feature request, where instead of the user having to copy and paste the entire team into the importable section of the team builder, the user instead just pastes the link of the pokepaste into it, and it auto generates the team. 

So instead of having to do this:
![image](https://user-images.githubusercontent.com/20847319/64287600-1e946e00-cf2e-11e9-872e-85fc4337a420.png)

You can do this instead:
![image](https://user-images.githubusercontent.com/20847319/64287652-408df080-cf2e-11e9-9529-93ef29eb291f.png)

And then it autogenerates the team
![image](https://user-images.githubusercontent.com/20847319/64287700-64513680-cf2e-11e9-8587-14f55fc9c796.png)

**Comment by HarounAns** [comment]
Sorry, just realized this was the github for pokepaste, not for Pokemon Showdown, gonna make this an issue for Showdown

**Comment by felixphew** [comment]
I believe the Showdown people are already working on this - see https://github.com/Zarel/Pokemon-Showdown-Client/issues/1349
