### ISSUE TITLE
Are there plans to add images for gen 8 Pokemon?

### ISSUE THREAD

**Issue by jamesqo** [felixphew/pokepaste#98]

**Comment by felixphew** [comment]
Yes, but currently no Dream World-style art has been released for any Gen 8 pokemon. I'm looking into options.

**Comment by ashcoding** [comment]
Any way to put a temp image for all images that does not render/exist? Currently it's a broken image.

**Comment by jamesqo** [comment]
^ Perhaps we could just put Bulbapedia-style images for the time being while we wait for the Dream World artwork to come out?

**Comment by Je40xx** [comment]
^ yeah I would rather have mismatched artstyles than just no images. Not even sure if dream world art will come for gen 8 too right?

**Comment by nmehta94** [comment]
Wouldn't using the images found on Serebii or Bulbapedia be sufficient for now? 
e.g. - https://www.serebii.net/swordshield/pokemon/555-g.png

**Comment by felixphew** [comment]
@jamesqo @mapler101 I've tried to get permission from Serebii to use their images, but Joe hasn't got back to me yet, and I'm not willing to scrape them as I know he's taken issue with others doing that in the past.

**Comment by felixphew** [comment]
I'm now looking into getting permission to use Smogon's images.

**Comment by jamesqo** [comment]
@felixphew Thanks for your efforts, please keep us updated!

**Comment by felixphew** [comment]
OK, so sorry about the delay, I've had a lot happening in my life lately. I notice that Dream World sprites are kicking around for SwSh, but for the life of me I can't work out where they're from. Do people know where these can be found?

Note that scraping from (e.g.) Bulbapedia is not a solution, as not only am I not sure if that's OK, but they've been cropped away from their original square aspect ratio.

**Comment by Akiak7** [comment]
> OK, so sorry about the delay, I've had a lot happening in my life lately. I notice that Dream World sprites are kicking around for SwSh, but for the life of me I can't work out where they're from. Do people know where these can be found?
> 
> Note that scraping from (e.g.) Bulbapedia is not a solution, as not only am I not sure if that's OK, but they've been cropped away from their original square aspect ratio.

They're from the Japanese Pokemon Center website

source: https://twitter.com/JosephTico/status/1229261211289706496

edit: here's the website https://www.pokemoncenter-online.com/?s=search/a

**Comment by felixphew** [comment]
@Akiak7 Thank you so much, that's exactly what I was looking for! The new images should be live now - I'd appreciate it if you'd all give it a try and see if anything's missing. (Note: there are no Gmax images. I'm thinking about how to handle that.)

**Comment by felixphew** [comment]
I've made a paste containing all the added images [here](https://pokepast.es/33da793374f12c0b).

**Comment by Akiak7** [comment]
@felixphew Awesome :)

Just one thing, my team has Indeedee-F, which doesn't show up (even though she has an image)

edit: wait nvm, the image is male Indeedee...

**Comment by felixphew** [comment]
I'm leaving this issue open to track the missing art for alternate forms (of which Indeedee-F, Toxitricity-Low-Key and Gmax are going to be the most relevant).

**Comment by Akiak7** [comment]
I think you should consider adding the regular art for the Gmax mons, or just use the Gmax art

Heck maybe even use Indeedee-M and Toxtricity HK, I feel like that would still be better than the missing image

Although it's up to you, I just don't really see how we're gonna get any more art in the future

**Comment by felixphew** [comment]
This should be fixed now, on the data side by 617fd20 and on the images side by the images I've switched to. Let me know if anything's still missing, and I'll be happy to reopen this. Sorry about the ridiculous delay!

**Comment by naderaaa** [comment]
This project is currently missing all Pokemon discovered in Legends Arceus, Scarlet and Violet's DLCs, and Legends ZA.
